[package]
name = "filemng"
version = "1.0.0"
authors = ["TRGT"]
edition = "2021"

[dependencies]
console_engine = {version = "2.4.0", features = ["event", "form"]}
crossterm = "0.23"
filesize = "0.2"
fs_extra = "1.2"



