[package]
name = "filemng"
version = "1.0.0"
authors = ["TRGT"]
edition = "2018"

[dependencies]
tui = { version = "0.16.0", default-features = false, features = ['crossterm'] }
crossterm = "0.22.1"




